"""Fixes

Revision ID: 83b2c7282b61
Revises: c027a14408f3
Create Date: 2024-05-31 17:19:37.030479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83b2c7282b61'
down_revision = 'c027a14408f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_books_cover_covers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_cover_id_covers'), 'covers', ['cover_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('cover')

    with op.batch_alter_table('genre_to_book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_genre_to_book_book_id_books', type_='foreignkey')
        batch_op.drop_constraint('fk_genre_to_book_genre_id_genres', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_genre_to_book_book_id_books'), 'books', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_genre_to_book_genre_id_genres'), 'genres', ['genre_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_book_id_books', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_book_id_books'), 'books', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_book_id_books'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_reviews_book_id_books', 'books', ['book_id'], ['id'])

    with op.batch_alter_table('genre_to_book', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_genre_to_book_genre_id_genres'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_genre_to_book_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_genre_to_book_genre_id_genres', 'genres', ['genre_id'], ['id'])
        batch_op.create_foreign_key('fk_genre_to_book_book_id_books', 'books', ['book_id'], ['id'])

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_books_cover_id_covers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_cover_covers', 'covers', ['cover'], ['id'])
        batch_op.drop_column('cover_id')

    # ### end Alembic commands ###
