"""Fixes

Revision ID: 907b43b7399d
Revises: 83b2c7282b61
Create Date: 2024-05-31 17:54:51.390415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907b43b7399d'
down_revision = '83b2c7282b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre_to_book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_genre_to_book_genre_id_genres', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_genre_to_book_genre_id_genres'), 'genres', ['genre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre_to_book', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_genre_to_book_genre_id_genres'), type_='foreignkey')
        batch_op.create_foreign_key('fk_genre_to_book_genre_id_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
