"""Fixes

Revision ID: c551129b6671
Revises: 907b43b7399d
Create Date: 2024-05-31 19:36:43.057276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c551129b6671'
down_revision = '907b43b7399d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_cover_id_covers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_cover_id_covers'), 'covers', ['cover_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_cover_id_covers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_cover_id_covers', 'covers', ['cover_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
